// SPDX-FileCopyrightText: 2026 Laode Muhammad Al Fatih <lamualfa@gmail.com>
// SPDX-License-Identifier: SSPL-1.0

// GENERATED by scripts/embed-web-dist.mjs — do not edit by hand. This
// committed copy is an empty stub; release builds regenerate it from
// apps/web/dist before compiling the single-file binary.

export const webAssets: Record<string, { body: string; base64: boolean }> = {}
